// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4xtIQzAqlgoxFtHxe6SOe8WmWhbsIujc',
    appId: '1:302128133892:web:804eecb7387e354f328251',
    messagingSenderId: '302128133892',
    projectId: 'whatsapp-clone-5179b',
    authDomain: 'whatsapp-clone-5179b.firebaseapp.com',
    storageBucket: 'whatsapp-clone-5179b.appspot.com',
    measurementId: 'G-WHF9PSN0R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGz6vc-rfiaDF8O5v1H7VoqY4D--mU4Cs',
    appId: '1:302128133892:android:cc655a64a1972e38328251',
    messagingSenderId: '302128133892',
    projectId: 'whatsapp-clone-5179b',
    storageBucket: 'whatsapp-clone-5179b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGWNBv0YJp9WmEAxWvYDdE-wRVwfl-Wok',
    appId: '1:302128133892:ios:bfa64ef59c79687c328251',
    messagingSenderId: '302128133892',
    projectId: 'whatsapp-clone-5179b',
    storageBucket: 'whatsapp-clone-5179b.appspot.com',
    iosClientId: '302128133892-l0tnc9ugmkiga4vn8tm9e06ogq4qfqmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
